version: '3.4'

networks:
  microservice-network:
    external: true
services:
  nginx:
    image: reverse-proxy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - microservice-network
    volumes:
      - ./letsencrypt:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'