version: '3.4'

networks:
  microservice-network:
    external: true
services:
  nginx:
    image: michaelbaudino/nginx-letsencrypt-reverse-proxy
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - microservice-network
    volumes:
      - letsencrypt-data:/etc/letsencrypt/
    environment:
      - BACKEND=api-gateway:3000
      - HSTS=true

volumes:
  letsencrypt-data:
    driver: local