version: '3.4'

networks:
  microservice-network:
    external: true
services:
  nginx:
    image: reverse-proxy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    environment:
      - API_GATEWAY_HOST=api-gateway
      - API_GATEWAY_PORT=3000
    ports:
      - 80:80
    networks:
      - microservice-network