version: '3.4'

networks:
  microservice-network:
    external: true
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 80:80
    networks:
      - microservice-network