version: '3.4'

networks:
  microservice-network:
    external: true
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - microservice-network
    volumes:
      - certs:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - ./letsencrypt:/var/log/letsencrypt
    networks:
      - microservice-network
    command: certonly --webroot --webroot-path=/var/www/certbot \
      --email alimanssouri221@gmail.com \
      --agree-tos \
      --no-eff-email \
      -d alimansoori.com

volumes:
  certs: