version: '3.8'

services:
  api-gateway:
    build: ../api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"
      - "4000:8080"
    volumes:
      - ../api-gateway/src:/usr/src/app/src
      - ../api-gateway/documentation:/usr/src/app/documentation 
    command: sh -c "npx @compodoc/compodoc -p tsconfig.json -s && npm run start:dev"
    environment:
      - NODE_ENV:development
      - PORT:3000
    networks:
      - backend
      - frontend

  users-service:
    build: ../services/users-service
    container_name: users-service
    restart: always
    ports:
      - "4001:8080"
    volumes:
      - ../services/users-service/src:/usr/src/app/src
      - ../services/users-service/documentation:/usr/src/app/documentation
    command: sh -c "npx @compodoc/compodoc -p tsconfig.json -s && npm run start:dev"
    networks:
      - backend
    links:
      - mysql_users_db
    environment:
      - NODE_ENV:development

  mysql_users_db:
    image: mysql:8.0
    container_name: mysql_users_db
    restart: on-failure
    ports:
      - "3308:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=users_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=secret
      - MYSQL_TCP_PORT=3307
    volumes:
      - mysql_users_db:/var/lib/mysql
    networks:
      - backend

  payments-service:
    build: ../services/payments-service
    container_name: payments-service
    restart: always
    ports:
      - "4002:8080"
    volumes:
      - ../services/payments-service/src:/usr/src/app/src
      - ../services/payments-service/documentation:/usr/src/app/documentation
    command: sh -c "npx @compodoc/compodoc -p tsconfig.json -s && npm run start:dev"
    networks:
      - backend
    links:
      - mysql_payments_db
    environment:
      - NODE_ENV:development

  mysql_payments_db:
    image: mysql:8.0
    container_name: mysql_payments_db
    restart: on-failure
    ports:
      - "3309:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=payments_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=secret
      - MYSQL_TCP_PORT=3307
    volumes:
      - mysql_payments_db:/var/lib/mysql
    networks:
      - backend

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - backend

#Volumes
volumes:
  mysql_users_db:
    driver: local
  mysql_payments_db:
    driver: local

networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure