version: '3.8'

services:
  api-gateway:
    build: ../api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ../api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT:3000
    networks:
      - backend
      - frontend

  users-service:
    build: ../users-service
    container_name: users-service
    restart: always
    volumes:
      - ../users-service/src:/usr/src/app/src
    command: npm run start:dev
    networks:
      - backend
    links:
      - mysql_users_db

  mysql_users_db:
    image: mysql:8.0
    container_name: mysql_users_db
    restart: on-failure
    ports:
      - "3308:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=users_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=secret
      - MYSQL_TCP_PORT=3307
    volumes:
      - mysql_users_db:/var/lib/mysql
    networks:
      - backend

  payments-service:
    build: ../payments-service
    container_name: payments-service
    restart: always
    volumes:
      - ../payments-service/src:/usr/src/app/src
    command: npm run start:dev
    networks:
      - backend
    links:
      - mysql_payments_db

  mysql_payments_db:
    image: mysql:8.0
    container_name: mysql_payments_db
    restart: on-failure
    ports:
      - "3309:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=payments_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=secret
      - MYSQL_TCP_PORT=3307
    volumes:
      - mysql_payments_db:/var/lib/mysql
    networks:
      - backend

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - backend

#Volumes
volumes:
  mysql_users_db:
    driver: local
  mysql_payments_db:
    driver: local

networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure