services:
  api-gateway:
    build:
      context: ../api-gateway
      target: production
    restart: always
    command: npm run start:prod

  api-gateway-documentation:
    build:
      context: ../api-gateway
      target: production

  users-service:
    build:
      context: ../services/users-service
      target: production
    command: npm run start:prod

  users-service-documentation:
    build:
      context: ../services/users-service
      target: production

  payments-service:
    build:
      context: ../services/payments-service
      target: production
    command: npm run start:prod

  payments-service-documentation:
    build:
      context: ../services/payments-service
      target: production