version: '3.4'

services:
  api-gateway:
    build:
      context: ../api-gateway
      target: production
    command: npm run start:prod
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    networks:
      - microservice-network

  # api-gateway-documentation:
  #   build:
  #     context: ../api-gateway
  #     target: production
  #   container_name: api-gateway-documentation
  #   restart: always
  #   ports:
  #     - "4000:8080"
  #   command: npx @compodoc/compodoc -p tsconfig.json -s
  #   env_file:
  #     - ../.env
  #   networks:
  #     - microservice-network

  users-service:
    build:
      context: ../services/users-service
      target: production
    command: npm run start:prod
    container_name: users-service
    restart: always
    networks:
      - microservice-network
    links:
      - mysql_users_db
    env_file:
      - ../.env

  mysql_users_db:
    image: mysql:8.0
    container_name: mysql_users_db
    restart: on-failure
    ports:
      - "3308:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=users_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=secret
      - MYSQL_TCP_PORT=3307
    volumes:
      - mysql_users_db:/var/lib/mysql
    networks:
      - microservice-network

  # users-service-documentation:
  #   build:
  #     context: ../services/users-service
  #     target: production
  #   container_name: users-service-documentation
  #   restart: always
  #   ports:
  #     - "4001:8080"
  #   command: npx @compodoc/compodoc -p tsconfig.json -s
  #   env_file:
  #     - ../.env
  #   networks:
  #     - microservice-network

  payments-service:
    build:
      context: ../services/payments-service
      target: production
    command: npm run start:prod
    container_name: payments-service
    restart: always
    volumes:
      - ../services/payments-service/src:/usr/src/app/src
    networks:
      - microservice-network
    links:
      - mysql_payments_db
    env_file:
      - ../.env

  mysql_payments_db:
    image: mysql:8.0
    container_name: mysql_payments_db
    restart: on-failure
    ports:
      - "3309:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=payments_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=secret
      - MYSQL_TCP_PORT=3307
    volumes:
      - mysql_payments_db:/var/lib/mysql
    networks:
      - microservice-network

  # payments-service-documentation:
  #   build:
  #     context: ../services/payments-service
  #     target: production
  #   container_name: payments-service-documentation
  #   restart: always
  #   ports:
  #     - "4002:8080"
  #   command: npx @compodoc/compodoc -p tsconfig.json -s
  #   env_file:
  #     - ../.env
  #   networks:
  #     - microservice-network

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - microservice-network

volumes:
  mysql_users_db:
    driver: local
  mysql_payments_db:
    driver: local

networks:
  microservice-network:
    external: true