version: '3.3'

services:
  api-gateway:
    build:
      context: ../api-gateway
      target: development
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ../api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - ../.env
    networks:
      - backend
      - frontend

  api-gateway-documentation:
    build:
      context: ../api-gateway
      target: development
    container_name: api-gateway-documentation
    restart: always
    ports:
      - "4000:8080"
    command: npx @compodoc/compodoc -p tsconfig.json -s
    environment:
      - NODE_ENV:development
    networks:
      - backend

  users-service:
    build:
      context: ../services/users-service
      target: development
    container_name: users-service
    restart: always
    volumes:
      - ../services/users-service/src:/usr/src/app/src
    command: npm run start:dev
    networks:
      - backend
    links:
      - mysql_users_db
    environment:
      - NODE_ENV:development

  mysql_users_db:
    image: mysql:8.0
    container_name: mysql_users_db
    restart: on-failure
    ports:
      - "3308:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=users_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=secret
      - MYSQL_TCP_PORT=3307
    volumes:
      - mysql_users_db:/var/lib/mysql
    networks:
      - backend

  users-service-documentation:
    build:
      context: ../services/users-service
      target: development
    container_name: users-service-documentation
    restart: always
    ports:
      - "4001:8080"
    command: npx @compodoc/compodoc -p tsconfig.json -s
    environment:
      - NODE_ENV:development
    networks:
      - backend

  payments-service:
    build:
      context: ../services/payments-service
      target: development
    container_name: payments-service
    restart: always
    volumes:
      - ../services/payments-service/src:/usr/src/app/src
    command: npm run start:dev
    networks:
      - backend
    links:
      - mysql_payments_db
    environment:
      - NODE_ENV:development

  mysql_payments_db:
    image: mysql:8.0
    container_name: mysql_payments_db
    restart: on-failure
    ports:
      - "3309:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=payments_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=secret
      - MYSQL_TCP_PORT=3307
    volumes:
      - mysql_payments_db:/var/lib/mysql
    networks:
      - backend

  payments-service-documentation:
    build:
      context: ../services/payments-service
      target: development
    container_name: payments-service-documentation
    restart: always
    ports:
      - "4002:8080"
    command: npx @compodoc/compodoc -p tsconfig.json -s
    environment:
      - NODE_ENV:development
    networks:
      - backend

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - backend

#Volumes
volumes:
  mysql_users_db:
    driver: local
  mysql_payments_db:
    driver: local

networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure